from rest_framework import Serializers
from accounts.models import *
from django.utils.encoding import smart_str
from django.utils.encoding import force_bytes
from django.utils.encoding import DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from xml.dom import ValidationErr