# Generated by Django 5.0.6 on 2024-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='accounts/images/default_profile.jpg', null=True, upload_to='accounts/images'),
        ),
    ]
